name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Conan package manager.
        run: |
             ./setup.sh

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Test
        run: |
          $GITHUB_WORKSPACE/build/bin/asm-parser $GITHUB_WORKSPACE/resources/example_intel.asm > ./example_intel.json

      - uses: actions/upload-artifact@v2
        with:
          path: build/bin/asm-parser
